# Generated by Django 3.2.5 on 2021-08-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210818_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='number_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
