# Generated by Django 3.2.5 on 2021-09-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210821_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_courier',
            field=models.BooleanField(default=False),
        ),
    ]
