# Generated by Django 3.2.5 on 2021-08-05 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('orderPrice', models.IntegerField()),
                ('delivery', models.BooleanField(default=False)),
                ('exportationStatus', models.IntegerField(choices=[(0, 'Ожидается'), (1, 'В пути'), (2, 'Готово')], default=0)),
                ('cleanStatus', models.IntegerField(choices=[(0, 'Ожидается'), (1, 'В процессе'), (2, 'Готово')], default=0)),
                ('statusDelivery', models.IntegerField(choices=[(0, 'Ожидается'), (1, 'В пути'), (2, 'Готово')], default=0)),
                ('totalPrice', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('shoesType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shoestype')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.status')),
            ],
        ),
    ]
