# Generated by Django 3.2.5 on 2021-08-28 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderPrice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shoesType',
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('isDefect', models.BooleanField(default=False)),
                ('orderPrice', models.IntegerField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
        ),
    ]
