# Generated by Django 3.2.5 on 2021-09-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210828_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='unicId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
