# Generated by Django 3.2.5 on 2021-09-25 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_orderrate_orderrateimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrate',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_rates', to='main.order'),
        ),
        migrations.AlterField(
            model_name='orderrate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderrateimages',
            name='order_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_rate_images', to='main.orderrate'),
        ),
    ]
