export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDER_RATE = "GET_ORDER_RATE";
export const GET_ORDER = "GET_ORDER";
export const GET_USER_ORDERS = "GET_USER_ORDERS";
export const CHANGE_EXPORTATION_STATUS = "CHANGE_EXPORTATION_STATUS";
export const CHANGE_CLEAN_STATUS = "CHANGE_CLEAN_STATUS";
export const CHANGE_STATUS_DELIVERY = "CHANGE_STATUS_DELIVERY";
export const GET_EXPORTATION_LIST = "GET_EXPORTATION_LIST";
export const GET_CLEAN_LIST = "GET_CLEAN_LIST";
export const GET_DELIVERY_LIST = "GET_DELIVERY_LIST";
export const GET_DONE_LIST = "GET_DONE_LIST"
export const SET_ROUTE = "SET_ROUTE";
export const CREATE_MESSAGES = "CREATE_MESSAGES";
export const CREATE_ERROR_MESSAGES = "CREATE_ERROR_MESSAGES";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAIL = "AUTHENTICATION_FAIL";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const LOGIN_PHONE_SUCCESS = "LOGIN_PHONE_SUCCESS";
export const LOGIN_PHONE_FAIL = "LOGIN_PHONE_FAIL";
export const VERIFY_PHONE_FAIL = "VERIFY_PHONE_FAIL";
export const VERIFY_PHONE_SUCCESS = "VERIFY_PHONE_SUCCESS";
export const SET_ISLOADING_TRUE = "SET_ISLOADING_TRUE";
export const SET_ISLOADING_FALSE = "SET_ISLOADING_FALSE";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";
export const CONFIG = {
    headers:{
        'Content-Type': 'application/json',
        'Authorization': `JWT ${localStorage.getItem('access')}`,
        'Accept': 'application/json'
    }
}
